### ISSUE TITLE
Not working with WoW 11.0 (TWW)

### ISSUE THREAD

**Issue by arcadepro** [enthh/overshields#2]
No overlay is shown on default raid frames. No errors thrown in bugsack.

**Comment by enthh** [comment]
Looks like the Blizz unit frames have changed in TWW. This will take some time to investigate.

**Comment by enthh** [comment]
I tested this with Raid Style unit frames in a follower dungeon and the Overshields are showing on the Raid Frames. Disabling the addon hides the overshields (just the normal glow).

Looks like it's working as expected. I'll update the version so you don't need to load outdated addons.

**Comment by arcadepro** [comment]
I'll re-check tomorrow. There might be something broken on the toon I used if that's the case.

**Comment by arcadepro** [comment]
Can confirm it's working fine now. I assume there was some issue on the character I initially tested on.
